### ISSUE TITLE
Dremio Cloner with Cloud:  ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None)

### ISSUE THREAD

**Issue by cmillerja** [deane-dremio/dremio-cloner#45] opened 2024-02-19 11:10 UTC
I am trying to test Dremio Cloner with Cloud.  I have followed the readme at https://github.com/deane-dremio/dremio-cloner/blob/master/README.md.

However, when attempting to perform a PUT to Cloud I encounter the following error:

File "C:\Python\Lib\site-packages\requests\adapters.py", line 501, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))

Here is an excerpt from the config_write_dir.json file:

{"dremio_cloner": [
{"command":"put"},
{"target": [
    {"endpoint": "http://api.eu.dremio.cloud/"},
    {"username": ""},
    {"password": ""},
    {"verify_ssl": "True"},
  {"is_community_edition": "False"},
{"is_dremio_cloud": "True"},
{"dremio_cloud_org_id": "#########################"},
{"dremio_cloud_project_id": "###############"}
]
},

**Comment by mxmarg** [comment] 2024-02-20 08:06
Hi @cmillerja,
I hope you are doing well :)

I just tested a Cloner put operation against Dremio Cloud EU, which created multiple folders and views, without issue.

The error `An existing connection was forcibly closed by the remote host` is unlikely to be caused by Cloner directly and more likely a general network or configuration issue, e.g. on the level of your Python requests library or possibly the network you were using to connect to DC.

**Comment by tolbrooker** [comment] 2024-02-20 09:44
Also, for your reference, I dont get this error when using a dry run.

**Comment by cmillerja** [comment] 2024-02-23 10:50
Also, for your reference, a get/read works fine.

**Comment by dremioJonny** [comment] 2024-02-27 14:26
@cmillerja - the issue is your endpoint (http://api.eu.dremio.cloud/). This should be https, i.e. https://api.eu.dremio.cloud/.

**Comment by tolbrooker** [comment] 2024-02-27 14:36
Thanks @dremioJonny.

**Closed** 2024-02-28 07:19 UTC
